name: climdat
channels:
- defaults
- conda-forge
dependencies:
- pip
- sphinx
- nbsphinx
# python
- python=3
- notebook
- pip
##############
# analytics
- xarray
- xclim
- dask
- nc-time-axis
# ############
# Data access
- esgf-pyclient
- myproxyclient
- pydap

##############
# plotting
- matplotlib
- cartopy
##############
# pip install
- pip:
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
